language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode8.3
      sudo: required

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://github.com/odaceo/script-ubuntu-swiftenv/raw/master/install.sh)" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install uuid-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ossp-uuid ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift build --configuration release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift test ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift build --configuration release -Xlinker -L/usr/local/lib/ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift test -Xlinker -L/usr/local/lib/ ; fi
